#!/usr/bin/env zsh

# ☁️ google cloud sdk ☁️
source "$HOME/.nix-profile/google-cloud-sdk/path.zsh.inc"

# nvm nstalled with the script from
# https://github.com/nvm-sh/nvm#installing-and-updating
NVM_DIR="$HOME/.nvm"

if [ -d "$NVM_DIR" ]; then
    export NVM_DIR;
    # NVM stuff - install with brew
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi

alias dcup="docker-compose up"
alias dcdown="docker-compose down"

##### FUNCTIONS ####

play() {
    cd /Users/brian/Code/local/play;
    code .;
}

db-mearas() {
    docker exec -it db-postgres-1 psql "postgresql://postgres:docker@0.0.0.0/mearas_development"
}

db-ts() {
    docker exec -it db-postgres-tenants-and-spaces-1 psql "postgresql://postgres:docker@0.0.0.0:5432/tenants_and_spaces"
}

grep-mearas() {
    rg "(^table_schema)|$@" -I < /Users/brian/Code/github/briankung-bpn/mearas-search/mearas_schema.csv | column -s, -t | cat -n
}

jira() {
    KEY="$1";
    open "https://bractlet.atlassian.net/browse/$KEY"
}
